server:
  port: 8090

spring:
  application:
    name: loans
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to ApexBank loans related local APIs"
  contactDetails:
    name: "JohnDoe - Developer"
    email: "john@ApexBank.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345

