spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to ApexBank loans related QA APIs"
  contactDetails:
    name: "Vijay Jamadar - QA Lead"
    email: "vijayj@ApexBank.com"
  onCallSupport:
    -(666) 265-3765
    -(666) 734-8371